# Python Data Science Handbook 課題集

-初心者
    -ジュピターノートの使い方

$a^2+b^2$

In [8]:
import numpy as np
import random
%timeit A=np.array([random.randint(0,100) for _ in range(1000)])

479 μs ± 2.22 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
%timeit A=[random.randint(0,100) for _ in range(1000)]

430 μs ± 3.24 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
np.linspace?
#区間内を均等に分割したリストを返す

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x00000113A1830AE0>
File:            e:\python\pdsh\venv\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    

In [12]:
np.random.rand?
#ランダムな行列を返す、行と列を指定する
np.random.rand(2,3)

array([[0.72476767, 0.83243871, 0.50917298],
       [0.54063323, 0.75739568, 0.18202743]])

Signature: np.random.rand(*args)
Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      method

In [37]:
np.random.randint(2,10)

2

In [13]:
np.random.rand(2,3)

array([[0.02205924, 0.48993329, 0.26956778],
       [0.76886073, 0.90110895, 0.60941604]])

In [39]:
SyntaxWarning?

Init signature: SyntaxWarning(self, /, *args, **kwargs)
Docstring:      Base class for warnings about dubious syntax.
Type:           type
Subclasses:     

In/Out履歴を使って前の計算結果を再利用するミニワークフローを示す。

In [40]:
import math

In [41]:
math.sin(2)

0.9092974268256817

In [42]:
math.cos(2)

-0.4161468365471424

In [43]:
In

['',
 "import numpy as np\nimport random\nget_ipython().run_line_magic('time', 'A=np.array([random.randint(0,100) for _ in range(100)])')",
 "import numpy as np\nimport random\nget_ipython().run_line_magic('time', '')\nA=np.array([random.randint(0,100) for _ in range(100)])\nprint(A)",
 "import numpy as np\nimport random\nget_ipython().run_line_magic('%time', '')\nA=np.array([random.randint(0,100) for _ in range(100)])\nprint(A)",
 "import numpy as np\nimport random\nget_ipython().run_line_magic('timeit', '')\nA=np.array([random.randint(0,100) for _ in range(100)])\nprint(A)",
 "import numpy as np\nimport random\nget_ipython().run_line_magic('timeit', '')\nA=np.array([random.randint(0,100) for _ in range(100)])",
 "import numpy as np\nimport random\nget_ipython().run_line_magic('timeit', 'A=np.array([random.randint(0,100) for _ in range(100)])')",
 "get_ipython().run_line_magic('timeit', 'A=[random.randint(0,100) for _ in range(100)]')",
 "import numpy as np\nimport random\nget_ipython

In [44]:
Out

{2: 'ok',
 3: 'ok',
 4: 'ok',
 5: 'ok',
 10: 'ok',
 11: 'ok',
 12: array([[0.72476767, 0.83243871, 0.50917298],
        [0.54063323, 0.75739568, 0.18202743]]),
 13: array([[0.02205924, 0.48993329, 0.26956778],
        [0.76886073, 0.90110895, 0.60941604]]),
 14: <bound method RandomState.bytes of RandomState(MT19937) at 0x113B7A0A140>,
 16: <bound method RandomState.bytes of RandomState(MT19937) at 0x113B7A0A140>,
 18: b'\xfe\x19|M\x8e',
 19: b'\xde\x8d\xfe\x19',
 20: 2,
 21: 3,
 22: 5,
 23: 9,
 24: 2,
 25: 9,
 26: 4,
 27: 3,
 28: 9,
 29: 8,
 30: 2,
 31: 8,
 32: 7,
 33: 8,
 34: 2,
 35: 5,
 36: 6,
 37: 2,
 41: 0.9092974268256817,
 42: -0.4161468365471424,
 43: ['',
  "import numpy as np\nimport random\nget_ipython().run_line_magic('time', 'A=np.array([random.randint(0,100) for _ in range(100)])')",
  "import numpy as np\nimport random\nget_ipython().run_line_magic('time', '')\nA=np.array([random.randint(0,100) for _ in range(100)])\nprint(A)",
  "import numpy as np\nimport random\nget_i

In [49]:
Out

{2: 'ok',
 3: 'ok',
 4: 'ok',
 5: 'ok',
 10: 'ok',
 11: 'ok',
 12: array([[0.72476767, 0.83243871, 0.50917298],
        [0.54063323, 0.75739568, 0.18202743]]),
 13: array([[0.02205924, 0.48993329, 0.26956778],
        [0.76886073, 0.90110895, 0.60941604]]),
 14: <bound method RandomState.bytes of RandomState(MT19937) at 0x113B7A0A140>,
 16: <bound method RandomState.bytes of RandomState(MT19937) at 0x113B7A0A140>,
 18: b'\xfe\x19|M\x8e',
 19: b'\xde\x8d\xfe\x19',
 20: 2,
 21: 3,
 22: 5,
 23: 9,
 24: 2,
 25: 9,
 26: 4,
 27: 3,
 28: 9,
 29: 8,
 30: 2,
 31: 8,
 32: 7,
 33: 8,
 34: 2,
 35: 5,
 36: 6,
 37: 2,
 41: 0.9092974268256817,
 42: -0.4161468365471424,
 43: ['',
  "import numpy as np\nimport random\nget_ipython().run_line_magic('time', 'A=np.array([random.randint(0,100) for _ in range(100)])')",
  "import numpy as np\nimport random\nget_ipython().run_line_magic('time', '')\nA=np.array([random.randint(0,100) for _ in range(100)])\nprint(A)",
  "import numpy as np\nimport random\nget_i

In [50]:
%magic


IPython's 'magic' functions

The magic function system provides a series of functions which allow you to
control the behavior of IPython itself, plus a lot of system-type
features. There are two kinds of magics, line-oriented and cell-oriented.

Line magics are prefixed with the % character and work much like OS
command-line calls: they get as an argument the rest of the line, where
arguments are passed without parentheses or quotes.  For example, this will
time the given statement::

        %timeit range(1000)

Cell magics are prefixed with a double %%, and they are functions that get as
an argument not only the rest of the line, but also the lines below it in a
separate argument.  These magics are called with two arguments: the rest of the
call line and the body of the cell, consisting of the lines below the first.
For example::

        %%timeit x = numpy.random.randn((100, 100))
        numpy.linalg.svd(x)

will time the execution of the numpy svd routine, running the assignment 

In [51]:
%lsmagic


Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %code_wrap  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %mamba  %matplotlib  %micromamba  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %uv  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%code_wrap  %%debug  %%file  %%html  %%javascript  %%js  %%l

In [52]:
%pwd

'e:\\Python\\PDSH'

In [53]:
%who

A	 math	 np	 random	 


In [55]:
%run?

Docstring:
Run the named file inside IPython as a program.

Usage::

  %run [-n -i -e -G]
       [( -t [-N<N>] | -d [-b<N>] | -p [profile options] )]
       ( -m mod | filename ) [args]

The filename argument should be either a pure Python script (with
extension ``.py``), or a file with custom IPython syntax (such as
magics). If the latter, the file can be either a script with ``.ipy``
extension, or a Jupyter notebook with ``.ipynb`` extension. When running
a Jupyter notebook, the output from print statements and other
displayed objects will appear in the terminal (even matplotlib figures
will open, if a terminal-compliant backend is being used). Note that,
at the system command line, the ``jupyter run`` command offers similar
functionality for executing notebooks (albeit currently with some
differences in supported options).

Parameters after the filename are passed as command-line arguments to
the program (put in sys.argv). Then, control returns to IPython's
prompt.

This is similar 

!ls（または!dir）と!echoを使って、NotebookからOSコマンドを実行し、結果をpandasで読み込む例を作る。

In [1]:
contents=!dir

In [6]:
with open('test.csv','w',encoding='utf-8') as f:
    for line in contents:
        line+='\n'
        f.writelines(line)

In [59]:
!dir /B > file_list.txt

In [61]:
import pandas as pd
df=pd.read_csv('file_list.txt',header=None,names=['filename'])
df


filename
0                             .gitignore
1                            basic.ipynb
2                          file_list.txt
3  PDSH_課題集_初心者-中級-上級_各100題 - Sheet1.csv
4                                   venv

%xmode Plain/Context/Verbose を切り替えて例外表示の違いを観察する。

In [66]:
%xmode Plain

Exception reporting mode: Plain


In [67]:
1/0

ZeroDivisionError: division by zero

In [68]:
%xmode Context

Exception reporting mode: Context


In [69]:
1/0

ZeroDivisionError: division by zero

In [70]:
%xmode Verbose

Exception reporting mode: Verbose


In [71]:
1/0

ZeroDivisionError: division by zero

%debug を使い、故意にエラーを出す関数のローカル変数を調べて原因を特定する。

In [14]:
def func1(a,b):
    return a/b

func1(1,2)


0.5

In [4]:
import numpy as np

リストから1次元ndarrayを作成し、dtypeとshapeを確認する。

In [5]:
A=[1,2,3,4]
arr=np.array(A)
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int64')

In [9]:
arr.shape

(4,)

zeros・ones・fullを使って 3x4 行列を3通りで生成し、値とdtypeの違いを比較する。

In [17]:
z=np.zeros([3,4],dtype=int)
print(z)
print(z.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64


In [21]:
o=np.ones([3,4],dtype=float)
print(o)
print(o.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [20]:
f=np.full([3,4],np.pi)
print(f)
print(f.dtype)

[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]
float64


np.random.default_rng を使ってシード固定の 5x5 乱数行列を作る。

In [81]:
rng1=np.random.default_rng(1)
rndA=rng1.random([5,5])
rndA


array([[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
       [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
       [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
       [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719]])

In [89]:
x1=rng1.integers(10,size=6)
print(x1)
print(x1[:3])
print(x1[2:4])
print(x1[3:])
print(x1[::2])

[6 5 9 7 0 1]
[6 5 9]
[9 7]
[7 0 1]
[6 9 0]


In [98]:
x2=rng1.integers(10,size=[5,5])
print(x2)
print(x2[:3,:3])
print(x2[::-1,::-1])
print(x2.T[::-1,::])

[[5 3 9 9 6]
 [3 5 5 0 0]
 [4 5 2 2 1]
 [9 5 2 7 9]
 [2 8 7 7 5]]
[[5 3 9]
 [3 5 5]
 [4 5 2]]
[[5 7 7 8 2]
 [9 7 2 5 9]
 [1 2 2 5 4]
 [0 0 5 5 3]
 [6 9 9 3 5]]
[[6 0 1 9 5]
 [9 0 2 7 7]
 [9 5 2 2 7]
 [3 5 5 5 8]
 [5 3 4 9 2]]


スライスがビューであることを確認し、コピーとの違いを実験で示す。

In [110]:
y1=rng1.integers(10,size=6)
yy1=y1[:3]
yy1[0]=5
print(yy1,id(yy1[0]))
print(y1,id(y1[0]))


[5 4 7] 2400866133072
[5 4 7 1 3 2] 2400866133072


In [111]:
y1=rng1.integers(10,size=6)
yy1=y1[:3].copy()
yy1[0]=5
print(yy1,id(yy1[0]))
print(y1,id(y1[0]))


[5 5 1] 2400866131536
[1 5 1 3 6 7] 2400866139568


reshapeで 3x4 -> 2x6 -> 12 に変換し、元配列と同じメモリを共有しているか調べる。

In [113]:
B=rng1.integers(10,size=[3,4])
print(B,id(B[0][0]))
C=B.reshape([4,3])
C[0][0]=100
print(B,id(B[0][0]))
print(C,id(C[0][0]))

[[7 2 5 0]
 [8 9 3 5]
 [5 7 0 5]] 2400866133008
[[100   2   5   0]
 [  8   9   3   5]
 [  5   7   0   5]] 2400866133008
[[100   2   5]
 [  0   8   9]
 [  3   5   5]
 [  7   0   5]] 2400866133008


In [115]:
import random

In [120]:
%%timeit
a=[random.randint(0,10) for _ in range(10000)]
b=a[:] 

4.54 ms ± 21.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [123]:
%%timeit
a=[random.randint(0,10) for _ in range(10000)]
b=a.copy()

4.59 ms ± 73.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [124]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [125]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [127]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [128]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [129]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


加減乗除・累乗・剰余のベクトル化計算を示す。

In [130]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # 整数除算

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [135]:
print(np.sin(x*np.pi/4))
print(np.exp(x))
print(np.log1p(x))


[0.         0.70710678 1.         0.70710678]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229 1.38629436]


In [136]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(1, 10).reshape(3, 3), columns=['A', 'B', 'C'])
print(df)
#    A  B  C
# 0  1  2  3
# 1  4  5  6
# 2  7  8  9

# 軸なし: データ全体の合計
print(df.sum())  # 列ごとの合計が出力される
print(df.values.sum()) # numpyの配列に変換すると全体合計が取得できる
print(np.sum(df)) # 同じく、全体合計が取得できる

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
A    12
B    15
C    18
dtype: int64
45
A    12
B    15
C    18
dtype: int64


e:\Python\PDSH\venv\Lib\site-packages\numpy\_core\fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


2D配列でaxis=0/1の合計を比較する。

In [137]:
print(df.sum(axis=0))  # 各列の合計
# A    12
# B    15
# C    18
# dtype: int64

print(df.mean(axis=0)) # 各列の平均
# A    4.0
# B    5.0
# C    6.0
# dtype: float64

A    12
B    15
C    18
dtype: int64
A    4.0
B    5.0
C    6.0
dtype: float64


In [138]:
print(df.sum(axis=1))  # 各行の合計
# 0     6
# 1    15
# 2    24
# dtype: int64

print(df.max(axis=1)) # 各行の最大値
# 0    3
# 1    6
# 2    9
# dtype: int64

0     6
1    15
2    24
dtype: int64
0    3
1    6
2    9
dtype: int64


形状 (3,1) と (1,4) の配列を足して (3,4) を得る。

In [140]:
d31=np.array([[0],[1],[2]])
d14=np.array([0,1,2,3])
d34=d31+d14
d34

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])